### ISSUE TITLE
Publish to Nuget github action has been deprecated

### ISSUE THREAD

**Issue by martinbryant** [CompositionalIT/feliz-ag-grid#19]
The action is used in the github workflow

https://github.com/brandedoutcast/publish-nuget

**Comment by isaacabraham** [comment]
@martinbryant what is the problem though - does this no longer work? And if so, is there an alternative that we can use (or is that part of this issue - to investigate a newer way)?

**Comment by martinbryant** [comment]
It still works ok. It was something I noticed when the build failed for a recent release. I have done no investigation work to see if there is any replacement, this is just for visibility

**Comment by mattgallagher92** [comment]
According to the project's README

> You can replicate the functionality of this action & much more by using the offical tools like dotnet CLI or GitHub CLI etc.

**Comment by jwthomson** [comment]
Done!
