### ISSUE TITLE
Add data to code sample

### ISSUE THREAD

**Issue by ajwillshire** [CompositionalIT/feliz-ag-grid#2]
In the Ag-Grid code sample, we have the type, then the Feliz code, but no actual example data that would enable the code sample to be run immediately. This would be nice just to get something working.

Also, the data that is used for the example isn't displaying properly in the grid - the date is mismatching somewhere.

**Comment by teknikal-wizard** [comment]
It looks like there is Olympic data included in the sample now, so I'll close this down. Please reopen if necessary :)
