### ISSUE TITLE
Free vs Enterprise

### ISSUE THREAD

**Issue by JordanMarr** [CompositionalIT/feliz-ag-grid#31]
Do these bindings have support for any of the [AG Grid Enterprise](https://www.ag-grid.com/license-pricing/) edition features?
Specifically, I am interested in the [Cell Range Selection](https://www.ag-grid.com/react-data-grid/range-selection/) feature.
(I would imagine that feature may not even require any difference in the API as it may "just work".)

**Comment by JordanMarr** [comment]
Never mind, I found that there is a free trial to preview the enterprise edition. 
I am in the process of adding missing enterprise bindings as I try it out. I will send a PR with anything I add.

**Comment by Larocceau** [comment]
@JordanMarr sorry for the long wait, but we reworked your PR and it should be ready to merge this week or next! See #34

**Comment by Larocceau** [comment]
It's been merged! We separated the enterprise features in a separate module, so you don't see them when not using enterprise features
