### ISSUE TITLE
How to make cell text selectable?

### ISSUE THREAD

**Issue by zwpdbh** [CompositionalIT/feliz-ag-grid#6]
From ag-grid document: https://ag-grid.com/javascript-data-grid/selection-overview/#cell-text-selection
It says: 
If you want to use a regular text selection as if the grid were a regular table, set enableCellTextSelection=true and ensureDomOrder=true in the gridOptions.

How to set this in Feliz-ag-grid? 

Or how to select the text of a selected row? 
I could output certain information of a clicked row into console by:
AgGrid.onRowClicked
But I want to copy a selected （clicked on a row） row's text into clipboard.

**Comment by theprash** [comment]
I've added these 2 props and released a new version (v0.0.5) 😇
